name: Create Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git checkout -b release/${{ github.sha }}
          git push --set-upstream origin release/${{ github.sha }}

      - run: npm ci

      - run: npx lerna version --yes --conventional-commits --exact

      - id: version
        run: echo "$(node -e 'process.stdout.write(`::set-output version=${require("./lerna.json").version}`)')"

      - run: gh pr create --base main --title "Release ${{ steps.version.outputs.version }}" --body "Release ${{ steps.version.outputs.version }}"
