name: Publish
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Release')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - run: npm run build

      - run: npx lerna exec npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
